### ISSUE TITLE
Java or Python

### ISSUE THREAD

**Issue by sible777** [sible777/netsecProject2#1]
Need to decide on the language of implementation for this project.

**Comment by JoshCMoore** [comment]
At least for the initial client and server programs, I think it's best to build off of his existing programs in java, but for the brute force python seems like a solid bet.

**Comment by sible777** [comment]
Sounds good to me. We are also allowed to use existing tools for the brute force as well. So, personally I'm going to try to wrote my own tool and possibly use some existing ones as well just cuz.
