### ISSUE TITLE
Implement DES Encryption

### ISSUE THREAD

**Issue by JoshCMoore** [sible777/netsecProject2#17]
Encrypt message using DES and the shared secret

**Comment by sible777** [comment]
Please test the DES methods in the Crypto module. I made logic changes to them recently so I need to update the unit tests accoridingly. But, I believe that they should work current. 

DH is finished up as well. Just need to test encryption and decryption with the resulting shared secret DES 8byte key.

Perhaps you can go ahead and run tests with the DES methods on the 1000words.txt file.

See the master branch for all current working code.

**Comment by sible777** [comment]
DES Encryption and decryption is implemented. 

We can start doing the benchmarks for it on th 1000words.txt file now.

I will make an issue for that and assign it to you, I'm going to continue to work on implementing RSA stuff and key exchange. 

You may also want to go ahead and do some of your own crypt analysis on DES. We don't need to capture any traffic yet. If you look in the tests you can see how I set up things to DES encrypt and decrypt with predetermined keys and initialization vectors. You can simply grab that code and us it to write the tests to time how long it takes to decrypt and encrypt the wordlist if you want.
