### ISSUE TITLE
Implement Server Socket Communications

### ISSUE THREAD

**Issue by sible777** [sible777/netsecProject2#3]

**Comment by JoshCMoore** [comment]
[TextServer.txt](https://github.com/sible777/netsecProject2/files/843599/TextServer.txt)
Just a quick idea I'm working on for the diffie hellman protocol
The Client side is gonna essentially be the reverse of this, I'm gonna write that up tomorrow.  I'll clean the whole  thing up a bit after I make sure my implementation works

**Comment by sible777** [comment]
Looks good after a quick read over it. 
When you get that part of the diffie-helman working comment it in the issue for Diffie-helman that I've reassigned to you. Then I'll work on integrating it into the Crypto module so that I can implement the appropriate functionality into the client.

**Comment by JoshCMoore** [comment]
It occurs to me that I'm not entirely sure what you mean by this issue

**Comment by sible777** [comment]
It's redundant now. Since the socket stuff is already implement in the Server.
I'm going to close it.
