### ISSUE TITLE
Test DES Encryption and Decryption Times

### ISSUE THREAD

**Issue by sible777** [sible777/netsecProject2#8]
Test Wordlist:
https://www.dropbox.com/s/m3lny12jpr1hpym/10000words.txt?dl=0

@JoshCMoore If you look in the [tests](https://github.com/sible777/netsecProject2/blob/master/test/CryptoTest.java) you can see how I set up things to DES encrypt and decrypt with predetermined keys and initialization vectors. You can simply grab that code and us it to write the tests to time how long it takes to decrypt and encrypt the wordlist if you want. 

I would make a new branch for this if I were, something like DESTimes or what have you. Just make sure you branch off from the master as it's the most up to date and stable code right now.

**Comment by JoshCMoore** [comment]
So your testing file used libraries I don't have on my machine so I wrote up my own test program for DES that can also be used for Asymmetric encryption/decryption. I got 1.6 seconds for the encryption and 1.4 for the decryption (This doesn't count sending and receiving times, nor does it count generating the key.) If this seems off to you let me know but I'm adding these times to the writeup

**Comment by sible777** [comment]
Alright, I wrote some benchmarking code as well that we can just include in the source submission as well.  I will compare those times to my benchmarks as well. 

As for the unit tests, I think the test jars are in the test folder, all you need to do is make sure the the classes are compiled and then from the root dir run sh tests.sh That should run the unit tests as well as generate a log file of the results.


I'm working on Japanese and 553 hw tonight, but tomorrow I should have HMAC finished. Then we can both do traffic captures and such. I think you should go ahead and brain storm a brute force attempt. I have one figured up that I was going to run on my GPU but I haven't had time to implement it since everything has been so damn crazy.

**Comment by sible777** [comment]
Done
