### ISSUE TITLE
(optional) Implement Brute Force Tool (DES)

### ISSUE THREAD

**Issue by sible777** [sible777/netsecProject2#9]
This one is optional, as we could use existing tools. However, it's always a great experience to write your own security tools.

**Comment by JoshCMoore** [comment]
I wrote a java program that I believe does this, but I don't know how to get it to run through the GPU. If there's something that you see that can be optimized let me know.

**Comment by sible777** [comment]
I will take a peek at it once I do the HMAC benchmarking and put into the report. I benchmarked the enc and dec times for DES and RSA and they were similar to your times, within a small margin of error I think. I will have to check again, I think that my DES encryption was actually wayyyy faster like .29 seconds. Could just be a hardware thing though.

**Comment by sible777** [comment]
Closing this as the code is there, unfortunately I did not have the time to implement my own GPU based attempt. I will still likely do this after the fact in C using OpenCL.
